### ISSUE TITLE
Twitter weird response

### ISSUE THREAD

**Issue by amiref** [Jefferson-Henrique/GetOldTweets-python#111]
got3 works fine for me, however; for some queries, it suddenly crashes with this error:
Twitter weird response. Try to see on browser: 
Unexpected error: <class 'urllib.error.HTTPError'>

Does anybody know how I can resolve this issue?

**Comment by rodolfo-viana** [comment]
Just got the same issue here. It reads:

```
$ python Exporter.py --querysearch "#whatever"
Searching...

More 100 saved on file...

More 100 saved on file...

More 100 saved on file...

More 100 saved on file...

More 100 saved on file...

Twitter weird response. Try to see on browser: https://twitter.com/search?q=%20%23whatever&src=typd
Unexpected error: <class 'http.client.IncompleteRead'>
Done. Output file generated "output_got.csv".
Traceback (most recent call last):
  File "C:\Users\rodolfoviana\Documents\code\got\getoldtweets-python\got3\manager\TweetManager.py", line 128, in getJsonReponse
    jsonResponse = response.read()
  File "C:\ProgramData\Anaconda3\envs\got3\lib\http\client.py", line 462, in read
    s = self._safe_read(self.length)
  File "C:\ProgramData\Anaconda3\envs\got3\lib\http\client.py", line 614, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(54092 bytes read, 181812 more expected)
```

**Comment by MohamedChaawa** [comment]
This error is due to a bad connection quality.

**Comment by rodolfo-viana** [comment]
Actually it is because a period of time is not specified. When you enter two dates the error disappears.

**Comment by nscozzaro** [comment]
@rodolfo-viana I get the error randomly when I have only the "--since". Are you saying that I also have to include the "--until" in order to make the error go away?

**Comment by rodolfo-viana** [comment]
@nscozzaro I guess so. It only works for me when I include "--since" and "--until".

**Comment by VIgneshGV91** [comment]
I have given dates in both the "--since" and "--until" parameters. But still I am facing the following errors
I am trying to fetch tweets based on keyword search for a time frame of 6 months.... kindly help me resolving this issue


C:\Vignesh\Studies\Spring 18\Info Strategy & Policy\ADR Twitter Project\GetOldTweets-python-master>python Exporter.py --querysearch 'claritin' --since 2017-04-01 --until 2017-09-30 --maxtweets 10000
Searching...

Twitter weird response. Try to see on browser: https://twitter.com/search?q=&src=typd
Unexpected error: <class 'urllib.error.HTTPError'>
Done. Output file generated "output_got.csv".
Traceback (most recent call last):
  File "C:\Vignesh\Studies\Spring 18\Info Strategy & Policy\ADR Twitter Project\GetOldTweets-python-master\got3\manager\TweetManager.py", line 130, in getJsonReponse
    response = opener.open(url)
  File "C:\Users\vigne\Anaconda3\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\vigne\Anaconda3\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\vigne\Anaconda3\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\vigne\Anaconda3\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\vigne\Anaconda3\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Exporter.py", line 70, in main
    got.manager.TweetManager.getTweets(tweetCriteria, receiveBuffer)
  File "C:\Vignesh\Studies\Spring 18\Info Strategy & Policy\ADR Twitter Project\GetOldTweets-python-master\got3\manager\TweetManager.py", line 21, in getTweets
    json = TweetManager.getJsonReponse(tweetCriteria, refreshCursor, cookieJar, proxy)
  File "C:\Vignesh\Studies\Spring 18\Info Strategy & Policy\ADR Twitter Project\GetOldTweets-python-master\got3\manager\TweetManager.py", line 136, in getJsonReponse
    sys.exit()
SystemExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Exporter.py", line 79, in <module>
    main(sys.argv[1:])
  File "Exporter.py", line 72, in main
    except arg:
TypeError: catching classes that do not inherit from BaseException is not allowed

C:\Vignesh\Studies\Spring 18\Info Strategy & Policy\ADR Twitter Project\GetOldTweets-python-master>

**Comment by khaledmohammedsaifuddin** [comment]
VIgneshGV91 I am facing the same issue. Did you able to solve the problem?

**Comment by taruntiwarihp** [comment]
I am also facing same issue

**Comment by madawa111** [comment]
me too

**Comment by FilipeLang** [comment]
Same here

**Comment by priyabiswas12** [comment]
Same here. Has anyone resolved it?
