### ISSUE TITLE
'None Type' error

### ISSUE THREAD

**Issue by wuqui** [Jefferson-Henrique/GetOldTweets-python#140]
Hello,

first of all: thanks for this great tool!

I use the Python 2 version from the command line and I get a 'None Type' error in some of my queries. I can't figure out what the problem is. It occurs for some query terms and not for others. For example, the query `alt-right` (`python Exporter.py --querysearch "alt-right" --since 2017-01-01 --until 2017-08-01`) throws an error if I specify no limit or anything more than 100 max. tweets and never returns more than 100 tweets. The same query but with the term `alt-left`, however, doesn't throw an error and catches a lot (!) more (20,000 for the first run which went back until May). 

Could it depend on how many results there are to find? This would still be puzzling, as `alt-right` should produce more results than `alt-left`, so no reason to end searching for the former earlier than for the latter.

Here's the full error message:

```
Traceback (most recent call last):
  File "Exporter.py", line 79, in <module>
    main(sys.argv[1:])
  File "Exporter.py", line 70, in main
    got.manager.TweetManager.getTweets(tweetCriteria, receiveBuffer)
  File ".../GetOldTweets/got/manager/TweetManager.py", line 40, in getTweets
    retweets = int(tweetPQ("span.ProfileTweet-action--retweet span.ProfileTweet-actionCount").attr("data-tweet-stat-count").replace(",", ""));
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by hariskr** [comment]
Same issue, have you found a solution yet?

**Comment by wuqui** [comment]
Nope, unfortunately not. I had to manually go back in time from error to error. Pretty bad, this makes larger scale harvesting pretty much impossible... Let me know if you can come up with something!

**Comment by hariskr** [comment]
Will do, thanks for the reply. Btw, what do you mean 'manually go back in time error to error'?

Just an idea, but would it help to divide up the data collection into smaller chunks or smaller time windows? I.e., is it having trouble collecting all the data at once, or just collecting the data in general?

**Comment by wuqui** [comment]
I'm using it to harvest tweets retrospectively, surpassing Search APIs limit of 7--10 days to get tweets from e.g. two years ago. It seemed 'randomly' throw that error. Sometimes I manage to crawl e.g. 10,000 (covering a whole year) tweets without getting an error, other times it threw errors every 100 tweets (spanning only two days) or so. So I started a new search from where the error occurred to move back further. 

I don't know about all of this at all, but one thing which came to mind was that there might be some (sequence of) character(s) or so in some tweets that makes the script crash. This would explain the pretty random occurrence of errors which doesn't seem to be related to a limitation in total volume or Twitter blocking it or so.
