### ISSUE TITLE
Error in PyQuery when a username is not specified

### ISSUE THREAD

**Issue by Acciorocketships** [Jefferson-Henrique/GetOldTweets-python#146]
tweetCriteria = TweetCriteria().setMaxTweets(1).setQuerySearch('hello')
 tweets = TweetManager.getTweets(tweetCriteria)

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyquery/pyquery.py", line 66, in fromstring
    result = getattr(etree, meth)(context)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:82934)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124533)
  File "src/lxml/parser.pxi", line 1700, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:122964)
  File "src/lxml/parser.pxi", line 1040, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:116705)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 2, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sphericalcow/Downloads/TweetManager.py", line 71, in getTweets
    scrapedTweets = PyQuery(json['items_html'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyquery/pyquery.py", line 226, in __init__
    elements = fromstring(context, self.parser)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyquery/pyquery.py", line 70, in fromstring
    result = getattr(lxml.html, meth)(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lxml/html/__init__.py", line 867, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lxml/html/__init__.py", line 755, in document_fromstring
    "Document is empty")
lxml.etree.ParserError: Document is empty
>>>

**Comment by Acciorocketships** [comment]
It works if you add in the time window like in the example. I'm not sure if this is intentional, but I think it would be better if it still worked without a time window.
