### ISSUE TITLE
Upon running the code example in main.py, I am getting only one output despite setting the setMaxTweets to 1000. Also I don't get any output using custom search terms. Please help. I have written the error which arises. 

### ISSUE THREAD

**Issue by grilled-prawns** [Jefferson-Henrique/GetOldTweets-python#175]
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/siddharth/PycharmProjects/GetOldTweets-python-master/Main.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyquery/pyquery.py", line 66, in fromstring
    result = getattr(etree, meth)(context)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:82934)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124533)
  File "src/lxml/parser.pxi", line 1700, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:122964)
  File "src/lxml/parser.pxi", line 1040, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:116705)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 2, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/siddharth/PycharmProjects/GetOldTweets-python-master/Main.py", line 36, in <module>
    main()
  File "/Users/siddharth/PycharmProjects/GetOldTweets-python-master/Main.py", line 25, in main
    tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]
  File "/Users/siddharth/PycharmProjects/GetOldTweets-python-master/got3/manager/TweetManager.py", line 26, in getTweets
    scrapedTweets = PyQuery(json['items_html'])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyquery/pyquery.py", line 226, in __init__
    elements = fromstring(context, self.parser)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyquery/pyquery.py", line 70, in fromstring
    result = getattr(lxml.html, meth)(context)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lxml/html/__init__.py", line 867, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/lxml/html/__init__.py", line 755, in document_fromstring
    "Document is empty")
lxml.etree.ParserError: Document is empty

**Comment by Chrizzle123** [comment]
I can't reproduce the error you are describing. The examples work fine for me. Can you maybe attach your code?
Also make sure you remove the '[0]' from 'tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]' if you want to see more than one tweet

**Comment by tuhinjubcse** [comment]
Done. Output file generated "output_got.csv".
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pyquery/pyquery.py", line 66, in fromstring
    result = getattr(etree, meth)(context)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:82934)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124533)
  File "src/lxml/parser.pxi", line 1700, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:122964)
  File "src/lxml/parser.pxi", line 1040, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:116705)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 2, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Exporter.py", line 70, in main
    got.manager.TweetManager.getTweets(tweetCriteria, receiveBuffer)
  File "/Users/tuhinchakrabarty/Desktop/GetOldTweets-python/got3/manager/TweetManager.py", line 26, in getTweets
    scrapedTweets = PyQuery(json['items_html'])
  File "/usr/local/lib/python3.6/site-packages/pyquery/pyquery.py", line 226, in __init__
    elements = fromstring(context, self.parser)
  File "/usr/local/lib/python3.6/site-packages/pyquery/pyquery.py", line 70, in fromstring
    result = getattr(lxml.html, meth)(context)
  File "/usr/local/lib/python3.6/site-packages/lxml/html/__init__.py", line 867, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/local/lib/python3.6/site-packages/lxml/html/__init__.py", line 755, in document_fromstring
    "Document is empty")
lxml.etree.ParserError: Document is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Exporter.py", line 79, in <module>
    main(sys.argv[1:])
  File "Exporter.py", line 72, in main
    except arg:
TypeError: catching classes that do not inherit from BaseException is not allowed


SAME ERROR

**Comment by and-rewsmith** [comment]
A proxy will instantly fix the issue. This is the most common problem reported, so there should probably be some mention in the README.

One of the classes you use has a default param for adding a proxy. You'll have to find which one it is as I don't remember.

**Comment by and-rewsmith** [comment]
You have been IP blocked. Use a proxy to fix this issue. There is support for a proxy with the getTweets function.
