### ISSUE TITLE
Hashtags 

### ISSUE THREAD

**Issue by NICK7Z** [Jefferson-Henrique/GetOldTweets-python#260]
I was trying to get certain hashtags, the others in the example all worked, and I use this format in terminal 
python Exporter.py --hashtags "#everyday" --maxtweets 10

It returns me this error:
Traceback (most recent call last):
  File "Exporter.py", line 79, in <module>
    main(sys.argv[1:])
  File "Exporter.py", line 75, in main
    outputFile.close()
UnboundLocalError: local variable 'outputFile' referenced before assignment

How can I solve this?

Thanks

**Comment by JhonJDiazG** [comment]
Make sure that there is no other CSV file called "output_got.csv" in the folder where is Exporter.py. Pardon for my english.

**Comment by SurajMeena** [comment]
I think you should use --querysearch instead of --hashtags, it will work for sure
