### ISSUE TITLE
querysearch not working

### ISSUE THREAD

**Issue by rsingh2083** [Jefferson-Henrique/GetOldTweets-python#30]
Im running this code
`python Exporter.py --querysearch 'europe refugees' --maxtweets 10`

and got this error

```
Done. Output file generated "output_got.csv".
Traceback (most recent call last):
  File "Exporter.py", line 79, in <module>
    main(sys.argv[1:])
  File "Exporter.py", line 70, in main
    got.manager.TweetManager.getTweets(tweetCriteria, receiveBuffer)
  File "C:\Users\RAHUL_MSI\Anaconda2\lib\site-packages\got\manager\TweetManager.py", line 18, in getTweets
    if (tweetCriteria.username.startswith("\'") or tweetCriteria.username.startswith("\"")) and (tweetCriteria.username.
endswith("\'") or tweetCriteria.username.endswith("\"")):
AttributeError: TweetCriteria instance has no attribute 'username'
```

**Comment by Jefferson-Henrique** [comment]
Hello @rsingh2083 can you update the code and try again? By the way I have changed the examples to use double quotes like
```
python Exporter.py --querysearch "europe refugees"  --maxtweets 10
```
