### ISSUE TITLE
ImportError: No module named _socket

### ISSUE THREAD

**Issue by Saan2mari** [Jefferson-Henrique/GetOldTweets-python#37]
Dear Jefferson

When I install requirments.txt, there are error "Import Error".

What can I do~?!

(venv) C:\Users\seoul1\Dropbox\Mari\GetOldTweets-python-master>pip install -r requirements.txt
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\seoul1\Dropbox\Mari\GetOldTweets-python-master\venv\Scripts\pip.exe__main__.py", line 5, in <module>
  File "c:\users\seoul1\dropbox\mari\getoldtweets-python-master\venv\lib\site-packages\pip__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "c:\users\seoul1\dropbox\mari\getoldtweets-python-master\venv\lib\site-packages\pip\utils__init__.py", line 22, in <module>
    from pip.compat import console_to_str, expanduser, stdlib_pkgs
  File "c:\users\seoul1\dropbox\mari\getoldtweets-python-master\venv\lib\site-packages\pip\compat__init__.py", line 13, in <module>
    from pip.compat.dictconfig import dictConfig as logging_dictConfig
  File "c:\users\seoul1\dropbox\mari\getoldtweets-python-master\venv\lib\site-packages\pip\compat\dictconfig.py", line 22, in <module>
    import logging.handlers
  File "C:\Python27\Lib\logging\handlers.py", line 26, in <module>
    import errno, logging, socket, os, cPickle, struct, time, re
  File "C:\Python27\Lib\socket.py", line 47, in <module>
    import _socket
ImportError: No module named _socket

**Comment by Jefferson-Henrique** [comment]
Hello @Saan2mari, it is not a common error, I suggest you to search on google, I saw this issue here for example: https://github.com/pypa/virtualenv/issues/72
