### ISSUE TITLE
Yesterday can run ,but today can not run

### ISSUE THREAD

**Issue by yanhuangxiaoguang** [Jefferson-Henrique/GetOldTweets-python#71]
i don't change code, run ,is this error:
Traceback (most recent call last):
  File "E:\...\src\GetOldTweets-python-master\Main.py", line 32, in <module>
    main()
  File "E:\...\src\GetOldTweets-python-master\Main.py", line 15, in main
    tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]
IndexError: list index out of range
——————————————————————————————
I think the reason is have no response, I change the url:
	def getJsonReponse(tweetCriteria, refreshCursor, cookieJar):
		url ="https://twitter.com/search?f=tweets&q=%s&src=typd%s"
Report errors:

  File "E:\Epyworkspace\pachong\src\twitter\GetOldTweets-python-master\Main.py", line 52, in <module>
    main()
  File "E:\Epyworkspace\pachong\src\twitter\GetOldTweets-python-master\Main.py", line 39, in main
    tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]
  File "E:\Epyworkspace\pachong\src\twitter\GetOldTweets-python-master\got\manager\TweetManager.py", line 26, in getTweets
    json = TweetManager.getJsonReponse(tweetCriteria, refreshCursor, cookieJar)
  File "E:\Epyworkspace\pachong\src\twitter\GetOldTweets-python-master\got\manager\TweetManager.py", line 155, in getJsonReponse
    dataJson = json.loads(jsonResponse)
  File "E:\Anaconda2\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "E:\Anaconda2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\Anaconda2\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

I hope to get help, thank you very much

**Comment by codypilot** [comment]
It looks like there aren't any tweets being returned for your specified query. The actual search is working properly, it's just that you're trying to access a tweet object at index 0 which does not exist.

**Comment by javamirier** [comment]
also got this issue - any solutions?

**Comment by yanhuangxiaoguang** [comment]
I take the author url ,open in the browser .  The browser will return a JSON file.  not a  html . The json file contains information about search results, but don't have detailed information,such as reply text and reply time and so on.  And this url will dont work in some times.I don't find reason.  if you want get tweets detaile information,plase change url .if you success ,please tell me .
Forgive me for my poor English.

**Comment by yanhuangxiaoguang** [comment]
@codypilot Yes. but sometime it will return three tweets results, I don't change code!
