### ISSUE TITLE
Error installing r-requirements.txt

### ISSUE THREAD

**Issue by AnaCnGarcia** [Jefferson-Henrique/GetOldTweets-python#79]
Hi, I get this error when installing the requirements. Do you have any idea why this is happening?

Thank you very much!

Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 274, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 145, in from_line
    elif os.path.isdir(path) and (os.path.sep in name or name.startswith('.')):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
TypeError: must be encoded string without NULL bytes, not str

Storing debug log for failure in /home/udocker/.pip/pip.log

**Comment by josephuses** [comment]
I get the same error.

**Comment by josephuses** [comment]
There are hidden characters in the file. Leaving

lxml
pyquery

worked for me.
