### ISSUE TITLE
Getting urlib2 not defined error

### ISSUE THREAD

**Issue by pranaych** [Jefferson-Henrique/GetOldTweets-python#83]
Hi I'm new to programming. I'm using python 2.7. I have downloaded the repository, unzipped it and had run the command pip install -r requirements.txt too to install the requirements. But i'm getting name 'urlib2' is not defined error when i run Main.py. Also, when i try to run Exporter.py, i'm getting a syntax error. Please find the error details below:

MacBook-Pro:GetOldTweets-python-master Pranay$ python Main.py
Traceback (most recent call last):
  File "Main.py", line 36, in <module>
    main()
  File "Main.py", line 19, in main
    tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/GetOldTweets-python-master/got3/manager/TweetManager.py", line 21, in getTweets
    json = TweetManager.getJsonReponse(tweetCriteria, refreshCursor, cookieJar, proxy)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/GetOldTweets-python-master/got3/manager/TweetManager.py", line 123, in getJsonReponse
    opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cookieJar))
NameError: name 'urllib2' is not defined

cBook-Pro:GetOldTweets-python-master Pranay$ python Exporter.py -h
  File "Exporter.py", line 14
    print f.read()
          ^
SyntaxError: invalid syntax

Can someone please help on this issue. Thanks.

**Comment by arujit** [comment]
I am not sure but I think it's a Python version clash error. Ideally as you are using Pyhton 2.7 the TweetManager.py script in python2.7/site-packages/GetOldTweets-python-master/got directory should be called. But in your case it calling the Python 3 supported got3/manager/TweetManager.py. As urllib also has Python version clashing issues, you are getting this error. I will for sure look into a method to resolve this.

**Comment by fernandoramacciotti** [comment]
I could manage this error by editing the TweetManager.py file in got3 folder. Basically there was some lines with urllib2 functions, I just put the corresponding Python 3.x

**Comment by aim0less** [comment]
@pranaych this is almost evident that you have Python 3.x active as environment. Now to ensure you can check python version. If you have python version >3.3.x, you might have python launcher installed. Python launcher enables you to choose the python version while executing the script. You may try running the script as:
py -2 Main.py
