### ISSUE TITLE
Setup.py Egg_info failed 

### ISSUE THREAD

**Issue by mike-m123** [Jefferson-Henrique/GetOldTweets-python#96]
Hello everyone, newbie here !!

I have tried running this on both python 2 and 3, the error persists. Python version to be exact 2.7.13. 

Here is the error message : 

Collecting git+https://github.com/Jefferson-Henrique/GetOldTweets-python
  Cloning https://github.com/Jefferson-Henrique/GetOldTweets-python to c:\users\hp\appdata\local\temp\pip-mcm4j9sg-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Anaconda3\lib\tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hp\\AppData\\Local\\Temp\\pip-mcm4j9sg-build\\setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\hp\AppData\Local\Temp\pip-mcm4j9sg-build\

**Comment by saurabhbidwai** [comment]
I'm also facing same issue

**Comment by XIEQ** [comment]
The package does not come with a setup.py file. You need to write your own setup.py file, then package it as an egg. If you just want to use Python 2 version directly from the cloned repo, just
```
cd  /path/to/GetOldTweets-python/got
import got
```
Then follow the example on the homepagge

**Comment by lapido** [comment]
`import sys
sys.path.append('/home/swissvic/code/python/data_science/sentiment_analysis/GetOldTweets/')

import got
`
This should work.
